services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=dbthuctap
      - MYSQL_ROOT_PASSWORD=Anhyeuem@0908
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  backend-spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9803:9803"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/dbthuctap
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Anhyeuem@0908
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PROJECT_UPLOAD_FILE_BASE_URI=file:///uploads/
    depends_on:
      db-mysql:
        condition: service_healthy
    volumes:
      - ../upload-docker/:/uploads/

volumes:
  mysql-data:
